# Generated by Django 5.2 on 2025-04-07 17:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название шаблона')),
                ('document_type', models.CharField(choices=[('order', 'Приказ'), ('contract', 'Договор'), ('act', 'Акт')], max_length=50, verbose_name='Тип документа')),
                ('template_file', models.FileField(upload_to='document_templates/', verbose_name='Файл шаблона')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fields_metadata', models.JSONField(default=dict, help_text='JSON структура с описанием полей для заполнения', verbose_name='Метаданные полей')),
            ],
            options={
                'verbose_name': 'Шаблон документа',
                'verbose_name_plural': 'Шаблоны документов',
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название документа')),
                ('description', models.CharField(blank=True, max_length=500, null=True, verbose_name='Описание документа')),
                ('status', models.CharField(choices=[('accept', 'Принят'), ('signed', 'Подписан'), ('pending', 'На подписании'), ('revision', 'На доработке')], default='pending', max_length=50, verbose_name='Статус документа')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('creators', models.ManyToManyField(related_name='created_documents', to=settings.AUTH_USER_MODEL, verbose_name='Создатели')),
                ('signed_by', models.ManyToManyField(blank=True, related_name='signed_documents', to=settings.AUTH_USER_MODEL, verbose_name='Подписавшие')),
                ('signers', models.ManyToManyField(related_name='documents_to_sign', to=settings.AUTH_USER_MODEL, verbose_name='Подписанты')),
            ],
            options={
                'verbose_name': 'Документ',
                'verbose_name_plural': 'Документы',
            },
        ),
        migrations.CreateModel(
            name='DocumentComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='Сообщение')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('is_system', models.BooleanField(default=False)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='Docs.document', verbose_name='Документ')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Комментарий к документу',
                'verbose_name_plural': 'Комментарии к документам',
            },
        ),
        migrations.CreateModel(
            name='DocumentFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='documents/%Y/%m/%d/', verbose_name='Файл')),
                ('name', models.CharField(max_length=255, verbose_name='Имя файла')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки')),
                ('status', models.CharField(choices=[('uploaded', 'Загружен'), ('deleted', 'Удален')], default='uploaded', max_length=50, verbose_name='Статус файла')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='Docs.document', verbose_name='Документ')),
            ],
            options={
                'verbose_name': 'Файл документа',
                'verbose_name_plural': 'Файлы документов',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('last_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Фамилия')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='profile_pics/', verbose_name='Фото профиля')),
                ('role', models.CharField(choices=[('employee', 'Сотрудник'), ('admin', 'Администратор'), ('director', 'Директор'), ('deputy_director', 'Заместитель директора'), ('secretary', 'Секретарь')], default='employee', max_length=50)),
                ('telegram_id', models.CharField(blank=True, max_length=100, null=True)),
                ('telegram_token', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
